name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        python-version: '3.11'
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y gdb libopenmpi-dev libssl-dev
    - name: Build example mpi program
      run: |
        make -C examples/
    - name: Install mdb and additional python packages
      run: |
        mkdir -p ~/.mdb
        openssl req -x509 -newkey rsa:4096 -sha256 -days 365 -keyout ~/.mdb/key.rsa -out ~/.mdb/cert.pem -nodes -subj "/C=XX/ST=mdb/L=mdb/O=mdb/OU=mdb/CN=localhost"
        ls ~/.mdb
        pip install -e .[develop,termgraph]
        MDB_LAUNCH_LOG_LEVEL="DEBUG" mdb launch -b gdb -t examples/simple-mpi.exe -n 2
    - name: Run tests
      run: |
        pytest --cov-report term-missing --cov-report json:cov.json --cov=mdb -vv tests/
    - name: Check coverage
      run: |
        python .github/workflows/coverage.py 60
